### ISSUE TITLE
Can't connect to parent instance

### ISSUE THREAD

**Issue by NadjaNeville** [AzuraCast/AzuraRelay#56]
Hello, 

I am trying to set up an instance of AzuraRelay, installation runs well with no errors then it comes to entry of the parent instance URL, the Relay seems to contact the parent just fine then throws an error missing a path. 

Parent is: [AzuraCast](https://www.azuracast.com/) • v0.17.6 Stable • Docker • PHP 8.1

Installation quits with an error that either URL or API key aren't specified.

[2023-01-18T05:01:37.692931+00:00] AzuraRelay.ERROR: TypeError: AzuraCast\Api\Dto\StationDto::__construct(): Argument #7 ($listenUrl) must be of type string, null given, called in /var/app/www/vendor/azuracast/php-api-client/src/Dto/StationDto.php on line 312 (uncaught exception) at /var/app/www/vendor/azuracast/php-api-client/src/Dto/StationDto.php line 70 while running console command `app:setup` {"exception":"[object] (TypeError(code: 0): AzuraCast\\Api\\Dto\\StationDto::__construct(): Argument #7 ($listenUrl) must be of type string, null given, called in /var/app/www/vendor/azuracast/php-api-client/src/Dto/StationDto.php on line 312 at /var/app/www/vendor/azuracast/php-api-client/src/Dto/StationDto.php:70)"} []
[2023-01-18T05:01:37.693836+00:00] AzuraRelay.WARNING: Console command `app:setup` exited with error code 1. [] []
[18-Jan-2023 05:01:37 UTC] PHP Fatal error:  Uncaught TypeError: AzuraCast\Api\Dto\StationDto::__construct(): Argument #7 ($listenUrl) must be of type string, null given, called in /var/app/www/vendor/azuracast/php-api-client/src/Dto/StationDto.php on line 312 and defined in /var/app/www/vendor/azuracast/php-api-client/src/Dto/StationDto.php:70
Stack trace:
#0 /var/app/www/vendor/azuracast/php-api-client/src/Dto/StationDto.php(312): AzuraCast\Api\Dto\StationDto->__construct(1, 'Neville Radio', 'neville_radio', 'A select collec...', 'remote', 'liquidsoap', NULL, true, Array, Array)
#1 /var/app/www/vendor/azuracast/php-api-client/src/Dto/NowPlayingDto.php(195): AzuraCast\Api\Dto\StationDto::fromArray(Array)
#2 /var/app/www/vendor/azuracast/php-api-client/src/Client.php(28): AzuraCast\Api\Dto\NowPlayingDto::fromArray(Array)
#3 /var/app/www/src/Console/Command/SetupCommand.php(62): AzuraCast\Api\Client->nowPlaying()
#4 /var/app/www/vendor/symfony/console/Helper/QuestionHelper.php(468): App\Console\Command\SetupCommand->App\Console\Command\{closure}('https://admin.s...')
#5 /var/app/www/vendor/symfony/console/Helper/QuestionHelper.php(75): Symfony\Component\Console\Helper\QuestionHelper->validateAttempts(Object(Closure), Object(Symfony\Component\Console\Style\SymfonyStyle), Object(Symfony\Component\Console\Question\Question))
#6 /var/app/www/vendor/symfony/console/Style/SymfonyStyle.php(348): Symfony\Component\Console\Helper\QuestionHelper->ask(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Style\SymfonyStyle), Object(Symfony\Component\Console\Question\Question))
#7 /var/app/www/src/Console/Command/SetupCommand.php(76): Symfony\Component\Console\Style\SymfonyStyle->askQuestion(Object(Symfony\Component\Console\Question\Question))
#8 /var/app/www/vendor/symfony/console/Command/Command.php(308): App\Console\Command\SetupCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/app/www/vendor/symfony/console/Application.php(1020): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/app/www/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Command\SetupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/app/www/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/app/www/bin/console(11): Symfony\Component\Console\Application->run()
#13 {main}
  thrown in /var/app/www/vendor/azuracast/php-api-client/src/Dto/StationDto.php on line 70

Fatal error: Uncaught TypeError: AzuraCast\Api\Dto\StationDto::__construct(): Argument #7 ($listenUrl) must be of type string, null given, called in /var/app/www/vendor/azuracast/php-api-client/src/Dto/StationDto.php on line 312 and defined in /var/app/www/vendor/azuracast/php-api-client/src/Dto/StationDto.php:70
Stack trace:
#0 /var/app/www/vendor/azuracast/php-api-client/src/Dto/StationDto.php(312): AzuraCast\Api\Dto\StationDto->__construct(1, 'Neville Radio', 'neville_radio', 'A select collec...', 'remote', 'liquidsoap', NULL, true, Array, Array)
#1 /var/app/www/vendor/azuracast/php-api-client/src/Dto/NowPlayingDto.php(195): AzuraCast\Api\Dto\StationDto::fromArray(Array)
#2 /var/app/www/vendor/azuracast/php-api-client/src/Client.php(28): AzuraCast\Api\Dto\NowPlayingDto::fromArray(Array)
#3 /var/app/www/src/Console/Command/SetupCommand.php(62): AzuraCast\Api\Client->nowPlaying()
#4 /var/app/www/vendor/symfony/console/Helper/QuestionHelper.php(468): App\Console\Command\SetupCommand->App\Console\Command\{closure}('https://admin.s...')
#5 /var/app/www/vendor/symfony/console/Helper/QuestionHelper.php(75): Symfony\Component\Console\Helper\QuestionHelper->validateAttempts(Object(Closure), Object(Symfony\Component\Console\Style\SymfonyStyle), Object(Symfony\Component\Console\Question\Question))
#6 /var/app/www/vendor/symfony/console/Style/SymfonyStyle.php(348): Symfony\Component\Console\Helper\QuestionHelper->ask(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Style\SymfonyStyle), Object(Symfony\Component\Console\Question\Question))
#7 /var/app/www/src/Console/Command/SetupCommand.php(76): Symfony\Component\Console\Style\SymfonyStyle->askQuestion(Object(Symfony\Component\Console\Question\Question))
#8 /var/app/www/vendor/symfony/console/Command/Command.php(308): App\Console\Command\SetupCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/app/www/vendor/symfony/console/Application.php(1020): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/app/www/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Command\SetupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/app/www/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/app/www/bin/console(11): Symfony\Component\Console\Application->run()
#13 {main}
  thrown in /var/app/www/vendor/azuracast/php-api-client/src/Dto/StationDto.php on line 70
[2023-01-18T05:01:37.694222+00:00] AzuraRelay.CRITICAL: Fatal error: Uncaught TypeError: AzuraCast\Api\Dto\StationDto::__construct(): Argument #7 ($listenUrl) must be of type string, null given, called in /var/app/www/vendor/azuracast/php-api-client/src/Dto/StationDto.php on line 312 and defined in /var/app/www/vendor/azuracast/php-api-client/src/Dto/StationDto.php:70 Stack trace: #0 /var/app/www/vendor/azuracast/php-api-client/src/Dto/StationDto.php(312): AzuraCast\Api\Dto\StationDto->__construct(1, 'Neville Radio', 'neville_radio', 'A select collec...', 'remote', 'liquidsoap', NULL, true, Array, Array) #1 /var/app/www/vendor/azuracast/php-api-client/src/Dto/NowPlayingDto.php(195): AzuraCast\Api\Dto\StationDto::fromArray(Array) #2 /var/app/www/vendor/azuracast/php-api-client/src/Client.php(28): AzuraCast\Api\Dto\NowPlayingDto::fromArray(Array) #3 /var/app/www/src/Console/Command/SetupCommand.php(62): AzuraCast\Api\Client->nowPlaying() #4 /var/app/www/vendor/symfony/console/Helper/QuestionHelper.php(468): App\Console\Command\SetupCommand->App\Console\Command\{closure}('https://admin.s...') #5 /var/app/www/vendor/symfony/console/Helper/QuestionHelper.php(75): Symfony\Component\Console\Helper\QuestionHelper->validateAttempts(Object(Closure), Object(Symfony\Component\Console\Style\SymfonyStyle), Object(Symfony\Component\Console\Question\Question)) #6 /var/app/www/vendor/symfony/console/Style/SymfonyStyle.php(348): Symfony\Component\Console\Helper\QuestionHelper->ask(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Style\SymfonyStyle), Object(Symfony\Component\Console\Question\Question)) #7 /var/app/www/src/Console/Command/SetupCommand.php(76): Symfony\Component\Console\Style\SymfonyStyle->askQuestion(Object(Symfony\Component\Console\Question\Question)) #8 /var/app/www/vendor/symfony/console/Command/Command.php(308): App\Console\Command\SetupCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #9 /var/app/www/vendor/symfony/console/Application.php(1020): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #10 /var/app/www/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Command\SetupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #11 /var/app/www/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #12 /var/app/www/bin/console(11): Symfony\Component\Console\Application->run() #13 {main}   thrown in /var/app/www/vendor/azuracast/php-api-client/src/Dto/StationDto.php on line 70 [] []
Error: No such container:path: azurarelay_relay:/var/app/www_tmp/azurarelay.env

**Comment by NadjaNeville** [comment]
found the issue myself
